FROM python:3.12-slim

WORKDIR /app/backend

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/*
COPY backend/ .

EXPOSE 5000

CMD [ "flask", "run", "--host=0.0.0.0", "--port=5000", "--debugger" ]

