FROM python:3.10-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN python -m venv .venv && .venv/bin/pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["/app/.venv/bin/python", "-m", "flask", "run", "--host=0.0.0.0", "--no-debugger"]