
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/*

ENV NODE_OPTIONS=--openssl-legacy-provider

COPY . .

EXPOSE 3000

CMD ["npm", "start"]