
name: CI Pipeline for Flask-React App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repo
        uses: actions/checkout@v4

      - name: Building Docker Images
        run: |
          docker build -f Dockerfile.backend -t back:1.0 .
          docker build -f Dockerfile.frontend -t front:1.0 . || (cat build-error.log && exit 1)

      - name: Running Containers
        run: |
          docker run -d -p 5000:5000 --name backend back:1.0
          docker run -d -p 3000:3000 --name frontend front:1.0
          sleep 5
          curl -f http://localhost:5000/profile || exit 1
          curl -f http://localhost:3000 || exit 1
          docker stop backend frontend
          docker rm backend frontend

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repo
        uses: actions/checkout@v4

      - name: Installing Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Installing NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Dockle
        run: |
          VERSION="0.4.14"
           curl -L -o dockle.deb "https://github.com/goodwithtech/dockle/releases/download/v${VERSION}/dockle_${VERSION}_Linux-64bit.deb"
           sudo dpkg -i dockle.deb
           rm dockle.deb

      - name: Dockle Test
        run : |
          docker pull mikamithejudgement/flask-react-back:latest || true
          docker pull mikamithejudgement/flask-react-front:latest || true
          dockle --exit-code 1 --exit-level FATAL mikamithejudgement/flask-react-back:latest
          dockle --exit-code 1 --exit-level FATAL mikamithejudgement/flask-react-front:latest

      - name: Unit Tests
        run: |
          cd backend
          pip install -r requirements.txt
          python -m pytest ../test/unit/backend || true
          cd ..
          npm ci
          npm test -- --watchAll=false || true

      - name: Style Tests
        run: |
          cd backend
          pip install flake8
          flake8 backend/ --config ../test/style/backend/flake8.ini || true
          cd ..
          npm ci
          npm run lint || true

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd DevOpsProject/
            git pull origin main
            chmod +x service-deploy.sh
            sudo ./service-deploy.sh          