
name: CI Pipeline for Flask-React App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repo
        uses: actions/checkout@v4

      - name: Building Docker Images
        run: |
          docker build -f Dockerfile.backend -t back:1.0 .
          docker build -f Dockerfile.frontend -t front:1.0 . || (cat build-error.log && exit 1)

      - name: Running Containers
        run: |
          docker run -d -p 5000:5000 --name backend back:1.0
          docker run -d -p 3000:3000 --name frontend front:1.0
          sleep 5
          curl -f http://localhost:5000/profile || exit 1
          curl -f http://localhost:3000 || exit 1
          docker stop backend frontend
          docker rm backend frontend

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repo
        uses: actions/checkout@v4

      - name: Installing Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Installing NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Unit Tests)
        run: |
          cd backend
          pip install -r requirements.txt
          python -m pytest ../test/unit/backend || true
          cd ..
          npm ci
          npm test -- --watchAll=false || true

      - name: Style Tests
        run: |
          cd backend
          pip install flake8
          flake8 backend/ --config ../test/style/backend/flake8.ini || true
          cd ..
          npm ci
          npm run lint || true
